# Generated by Django 4.0.3 on 2022-03-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddContractManager',
            fields=[
                ('ContractManagerId', models.IntegerField(primary_key=True, serialize=False)),
                ('ContractManagerName', models.CharField(max_length=100)),
                ('ContractManagerEmail', models.EmailField(max_length=50)),
                ('ContractManagerPhone', models.IntegerField(max_length=12)),
                ('ContractManager_ConstituencyId', models.CharField(max_length=50)),
                ('ContractManagerPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
