# Generated by Django 4.0.3 on 2022-06-09 19:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(default='Null', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('aadhaar_no', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='constituency',
            fields=[
                ('id', models.AutoField(default='Null', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('total_voters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='election_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_election', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='voter',
            fields=[
                ('id', models.AutoField(default='Null', primary_key=True, serialize=False)),
                ('voter_id', models.IntegerField(unique=True)),
                ('voter_aadhaar_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_votes', models.IntegerField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='voter_vote_status',
            fields=[
                ('id', models.AutoField(default='Null', primary_key=True, serialize=False)),
                ('casted_vote', models.BooleanField()),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.voter')),
            ],
        ),
        migrations.CreateModel(
            name='voter_constituency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loksabha_id', models.IntegerField()),
                ('vidhansabha_id', models.IntegerField()),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.voter')),
            ],
        ),
        migrations.CreateModel(
            name='constituency_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.constituency')),
                ('election_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.election_type')),
            ],
        ),
        migrations.CreateModel(
            name='candidate_party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.candidate')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.party')),
            ],
        ),
        migrations.CreateModel(
            name='candidate_constituency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.candidate')),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.constituency')),
                ('election_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.election_type')),
            ],
        ),
        migrations.CreateModel(
            name='booth_manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True)),
                ('aadhaar_no', models.CharField(max_length=50, unique=True)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.constituency')),
            ],
        ),
    ]
