# Generated by Django 4.0.3 on 2022-06-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter_id',
        ),
    ]
