# Generated by Django 4.0.3 on 2022-03-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_addcontractmanager_contractmanagerphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcontractmanager',
            old_name='ContractManagerPhone',
            new_name='ContractManagerPhoneNo',
        ),
    ]
