# Generated by Django 4.0.3 on 2022-06-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_remove_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
