# Generated by Django 4.0.3 on 2022-06-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_voter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter_aadhaar_no',
            new_name='aadhaar_no',
        ),
        migrations.AlterField(
            model_name='voter',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
