# Generated by Django 4.0.3 on 2022-03-31 05:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_rename_contractmanagerphone_addcontractmanager_contractmanagerphoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='booth_manager',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True)),
                ('aadhaar_no', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('aadhaar_no', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='candidate_constituency',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='candidate_party',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='constituency',
            fields=[
                ('constituency_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('total_voters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='constituency_type',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='contract_manager',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True)),
                ('aadhaar_no', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='election_type',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_election', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='voter',
            fields=[
                ('voter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('voter_aadhaar_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='voter_constituency',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('loksabha_id', models.IntegerField()),
                ('vidhansabha_id', models.IntegerField()),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.voter')),
            ],
        ),
        migrations.CreateModel(
            name='voter_vote_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casted_vote', models.BooleanField()),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.voter')),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('total_votes', models.IntegerField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.candidate')),
            ],
        ),
        migrations.DeleteModel(
            name='AddContractManager',
        ),
        migrations.AddField(
            model_name='constituency_type',
            name='election_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.election_type'),
        ),
        migrations.AddField(
            model_name='candidate_party',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.party'),
        ),
        migrations.AddField(
            model_name='candidate_constituency',
            name='constituency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.constituency'),
        ),
        migrations.AddField(
            model_name='candidate_constituency',
            name='election_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.election_type'),
        ),
        migrations.AddField(
            model_name='booth_manager',
            name='constituency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utility.constituency'),
        ),
    ]
