# Generated by Django 4.0.3 on 2022-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_rename_voter_aadhaar_no_voter_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
