# Generated by Django 4.0.3 on 2022-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_alter_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
